language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1.18
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - MAINTAINED_SYMFONY_VERSIONS="3.4.*|4.2.*"
    - LATEST_PHP_VERSION="7.3"
  matrix:
    - "TWIG_VERSION=2.4.* SYMFONY_VERSION=2.7.*"
    - "TWIG_VERSION=2.4.* SYMFONY_VERSION=2.8.*"
    - "TWIG_VERSION=2.4.* SYMFONY_VERSION=3.4.*"
    - "TWIG_VERSION=2.5.* SYMFONY_VERSION=3.4.*"
    - "TWIG_VERSION=2.6.* SYMFONY_VERSION=3.4.*"
    - "TWIG_VERSION=2.7.* SYMFONY_VERSION=3.4.*"
    - "TWIG_VERSION=2.4.* SYMFONY_VERSION=4.0.*"
    - "TWIG_VERSION=2.5.* SYMFONY_VERSION=4.0.*"
    - "TWIG_VERSION=2.6.* SYMFONY_VERSION=4.0.*"
    - "TWIG_VERSION=2.7.* SYMFONY_VERSION=4.0.*"
    - "TWIG_VERSION=2.4.* SYMFONY_VERSION=4.1.*"
    - "TWIG_VERSION=2.5.* SYMFONY_VERSION=4.1.*"
    - "TWIG_VERSION=2.6.* SYMFONY_VERSION=4.1.*"
    - "TWIG_VERSION=2.7.* SYMFONY_VERSION=4.1.*"
    - "TWIG_VERSION=2.4.* SYMFONY_VERSION=4.2.*"
    - "TWIG_VERSION=2.5.* SYMFONY_VERSION=4.2.*"
    - "TWIG_VERSION=2.6.* SYMFONY_VERSION=4.2.*"
    - "TWIG_VERSION=2.7.* SYMFONY_VERSION=4.2.*"
    - DEPENDENCIES="beta"
    - DEPENDENCIES="low"
    - DEPENDENCIES="stable"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES="beta"
    - env: DEPENDENCIES="low"

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ -n "$GH_TOKEN" ]; then
      composer config github-oauth.github.com ${GH_TOKEN};
    fi;
  - mkdir -p build/logs

install:
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      composer remove friendsofphp/php-cs-fixer phpstan/phpstan phpstan/phpstan-phpunit --dev --no-update;
    fi
  - if [ "$SYMFONY_VERSION" != "" && "$TWIG_VERSION" != "" ]; then
      composer remove symfony/symfony --dev --no-update &&
      composer require symfony/symfony:"${SYMFONY_VERSION}" --dev --no-update;
      composer remove twig/twig --no-update &&
      composer require twig/twig:"${TWIG_VERSION}" --no-update;
    fi
  - if [ "$DEPENDENCIES" = "beta" ]; then
      composer config minimum-stability beta;
      composer update -n --prefer-dist;
    elif [ "$DEPENDENCIES" = "low" ]; then
      composer update -n --prefer-dist --prefer-lowest;
    else
      composer update -n --prefer-dist;
    fi;
  - composer install --dev -o --prefer-dist

script:
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "File validation is skipped for older PHP versions";
    else
      composer validate-files;
    fi;
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "Static analysis is skipped for older PHP versions";
    else
      composer run-static-analysis-including-tests;
    fi;
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "Code style check is skipped for older PHP versions";
    else
      composer check-code-style;
    fi;
  - if [ "$MAINTAINED_SYMFONY_VERSIONS" != *"$SYMFONY_VERSION"* ]; then
      echo "Security check is skipped as Symfony $SYMFONY_VERSION is not actively maintained";
    elif [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "Security check is skipped due to security-checker issue 100";
    else
      composer check-security;
    fi;
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "Tests with reporting in Clover format are skipped for older PHP versions";
      composer run-tests;
    else
      composer run-tests-with-clover;
    fi;

after_script:
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "Coveralls report is skipped for older PHP versions";
    else
      bin/php-coveralls -v;
    fi;
